/**
 * Phoenix Mail Courier - Configuration
 * 
 * Centralized configuration for email triage operations.
 * In production, these can be loaded from SharePoint config files.
 */

const courierConfig = {
    // ==================== MAILBOX CONFIGURATION ====================
    mailboxes: [
        {
            id: 'shane',
            email: 'shane@phoenixelectric.life',
            name: 'Shane',
            enabled: true,
            priority: 1  // Process first
        },
        {
            id: 'stephanie',
            email: 'stephanie@phoenixelectric.life',
            name: 'Stephanie',
            enabled: true,
            priority: 2
        },
        {
            id: 'joe',
            email: 'joe@phoenixelectric.life',
            name: 'Joe',
            enabled: true,
            priority: 3
        },
        {
            id: 'info',
            email: 'info@phoenixelectric.life',
            name: 'Info (Shared)',
            enabled: true,
            priority: 4,
            isShared: true
        },
        {
            id: 'service',
            email: 'service@phoenixelectric.life',
            name: 'Service (Shared)',
            enabled: true,
            priority: 5,
            isShared: true
        }
    ],

    // ==================== SPAM/NEWSLETTER FILTERS ====================
    // Emails matching these patterns will be marked as read and skipped
    spamFilters: {
        // Domains to always skip
        domains: [
            'noreply@',
            'no-reply@',
            'donotreply@',
            'mailer-daemon@',
            'notifications@',
            'newsletter@',
            'marketing@',
            'promo@',
            'deals@'
        ],
        // Subject keywords to skip (case-insensitive)
        subjectKeywords: [
            'unsubscribe',
            'newsletter',
            'promotional',
            'sale ends',
            'limited time offer',
            'act now',
            'click here',
            'free gift'
        ],
        // Specific sender addresses to always skip
        blockedSenders: [
            // Add specific spam senders here
        ],
        // Auto-generated emails to skip (invoices, reports, etc.)
        autoGeneratedPatterns: [
            'automated report',
            'daily digest',
            'weekly summary',
            'system notification',
            'auto-generated'
        ]
    },

    // ==================== FOLDER MAPPINGS ====================
    // SharePoint folder structure for attachments
    sharePointConfig: {
        siteId: process.env.SHAREPOINT_SITE_ID || '',
        driveId: process.env.SHAREPOINT_DRIVE_ID || '',
        basePaths: {
            emailContacts: 'AI_Input/EmailContacts',
            logs: 'Logs/EmailTriage',
            output: 'AI_Output',
            memory: 'Phoenix Memory System'
        }
    },

    // ==================== SCHEDULING ====================
    schedule: {
        weekday: {
            times: ['09:00', '13:00', '17:00'],  // Mountain Time
            timezone: 'America/Denver'
        },
        weekend: {
            times: ['10:00'],  // Single run on weekends
            timezone: 'America/Denver'
        }
    },

    // ==================== PROCESSING LIMITS ====================
    limits: {
        maxEmailsPerRun: 50,           // Max emails to process per mailbox per run
        maxAttachmentSizeMB: 25,       // Skip attachments larger than this
        maxDraftLengthChars: 5000,     // Truncate drafts if longer
        processingDelayMs: 1000,       // Delay between emails to avoid throttling
        mailboxDelayMs: 5000           // Delay between mailboxes
    },

    // ==================== DRAFT GENERATION ====================
    draftGeneration: {
        enabled: true,
        model: 'gpt-4',
        // Template for draft subject lines
        subjectPrefix: '',  // e.g., '[AI Draft] ' - empty for clean drafts
        // Footer added to all AI-generated drafts
        draftFooter: '\n\n---\n(Draft prepared by Phoenix AI - Please review before sending)',
        // System prompt for generating email replies
        systemPrompt: `You are Phoenix, an AI assistant for Phoenix Electric, an electrical service company.
Your task is to draft professional, courteous email replies.

Guidelines:
1. Be concise and professional
2. Acknowledge the sender's message/request
3. Provide helpful information if available
4. If you cannot answer a question, say the team will follow up
5. Use a friendly but professional tone
6. Never make commitments or promises without explicit information
7. Sign off appropriately (e.g., "Best regards," or "Thank you,")
8. Keep drafts brief - typically 2-4 paragraphs max

Remember: This is a DRAFT that will be reviewed by a human before sending.`
    },

    // ==================== FLAGGING RULES ====================
    flaggingRules: {
        // Keywords that trigger flagging for follow-up
        urgentKeywords: [
            'urgent',
            'asap',
            'emergency',
            'immediate',
            'critical',
            'deadline'
        ],
        // Keywords indicating a question that needs answering
        questionIndicators: [
            '?',
            'can you',
            'could you',
            'would you',
            'please advise',
            'let me know',
            'what is',
            'when can',
            'how do'
        ],
        // Keywords indicating money/invoices
        financialKeywords: [
            'invoice',
            'payment',
            'quote',
            'estimate',
            'price',
            'cost',
            'bill'
        ]
    },

    // ==================== NOTIFICATIONS ====================
    notifications: {
        teamsEnabled: true,
        emailSummaryEnabled: false,  // Disabled per golden rule - no auto-sends
        // Teams channel for notifications
        teamsWebhookUrl: process.env.TEAMS_WEBHOOK_URL || '',
        // Notification thresholds
        notifyOnUrgent: true,
        notifyOnComplete: true,
        // Summary format
        summaryFormat: 'detailed'  // 'brief' or 'detailed'
    },

    // ==================== GOLDEN RULES (HARD GUARDRAILS) ====================
    goldenRules: {
        // NEVER send emails automatically - drafts only
        autoSendEnabled: false,
        // NEVER delete emails or attachments
        deleteEnabled: false,
        // NEVER modify original email content
        modifyOriginalEnabled: false,
        // Always log every action
        loggingRequired: true,
        // Always require human review for external communications
        humanReviewRequired: true
    }
};

/**
 * Get enabled mailboxes sorted by priority
 */
function getEnabledMailboxes() {
    return courierConfig.mailboxes
        .filter(m => m.enabled)
        .sort((a, b) => a.priority - b.priority);
}

/**
 * Check if a sender should be filtered as spam
 */
function isSpamSender(senderEmail, subject) {
    const email = senderEmail.toLowerCase();
    const subj = subject.toLowerCase();
    const filters = courierConfig.spamFilters;

    // Check domain patterns
    for (const domain of filters.domains) {
        if (email.includes(domain.toLowerCase())) {
            return true;
        }
    }

    // Check blocked senders
    if (filters.blockedSenders.some(s => email === s.toLowerCase())) {
        return true;
    }

    // Check subject keywords
    for (const keyword of filters.subjectKeywords) {
        if (subj.includes(keyword.toLowerCase())) {
            return true;
        }
    }

    // Check auto-generated patterns
    for (const pattern of filters.autoGeneratedPatterns) {
        if (subj.includes(pattern.toLowerCase())) {
            return true;
        }
    }

    return false;
}

/**
 * Determine if an email should be flagged for follow-up
 */
function shouldFlagEmail(subject, bodyPreview) {
    const text = `${subject} ${bodyPreview}`.toLowerCase();
    const rules = courierConfig.flaggingRules;

    // Check urgent keywords
    for (const keyword of rules.urgentKeywords) {
        if (text.includes(keyword.toLowerCase())) {
            return { flag: true, reason: 'urgent' };
        }
    }

    // Check for questions
    for (const indicator of rules.questionIndicators) {
        if (text.includes(indicator.toLowerCase())) {
            return { flag: true, reason: 'question' };
        }
    }

    // Check financial keywords
    for (const keyword of rules.financialKeywords) {
        if (text.includes(keyword.toLowerCase())) {
            return { flag: true, reason: 'financial' };
        }
    }

    return { flag: false, reason: null };
}

/**
 * Get SharePoint path for a user's email attachments
 */
function getAttachmentPath(userId, senderDomain) {
    const basePath = courierConfig.sharePointConfig.basePaths.emailContacts;
    // Clean the domain name for folder use
    const cleanDomain = senderDomain
        .replace(/[^a-zA-Z0-9]/g, '_')
        .replace(/_+/g, '_')
        .substring(0, 50);
    
    return `${basePath}/${userId}/${cleanDomain}`;
}

/**
 * Get log file path for current run
 */
function getLogFilePath() {
    const now = new Date();
    const date = now.toISOString().split('T')[0];
    const time = now.toTimeString().split(' ')[0].replace(/:/g, '');
    const basePath = courierConfig.sharePointConfig.basePaths.logs;
    
    return `${basePath}/EmailTriage_${date}_Run${time}.log`;
}

module.exports = {
    courierConfig,
    getEnabledMailboxes,
    isSpamSender,
    shouldFlagEmail,
    getAttachmentPath,
    getLogFilePath
};
